#!/bin/bash

#####################################################
# function name	: 	testMem							#
# description	: 	checks program for memory leaks	#
# parameters	: 	$1 = logFile					#
#					$2 = program name				#
#					$3 = input file					#
# return value	: 	0 - no memory leaks				#
#					1 - memory leaks found			#
#####################################################

valgrind --error-exitcode=1 --tool=memcheck ./$2 <$3 >$1 2>&1

if [ $? -eq 1 ]
then
	echo "Memory X"
 	exit 1
else
	echo "Memory V"
 	exit 0
fi
